### PR TITLE
Remove some unused dependencies in Dockerfile

### PR DESCRIPTION
**Pull request by hsiaoyi0504**
After testing, it seems to me these two dependencies don't need to be installed.

### CODE REVIEW

**Comment by dytk2134** [comment]
In my opinion, `git` might be necessary for some user to upgrade the version of remap-gff3.

**Comment by hsiaoyi0504** [comment]
I don't think so, usual setup should be run any git commands in original host OS, and build the container again.

**Comment by dytk2134** [comment]
What will you suggest user to do if user put their data in the old container and just want to upgrade the remap-gff3? Same as above?

**Comment by hsiaoyi0504** [comment]
That's what I suggest in the internal issue #657. Better usage would be mount the data into container. That is, separate the software and data part. Make the container as light weight as possible. Users can still install git by themselves.

**Pull request merged**
