### PR TITLE
Use local files to install container

### PR DESCRIPTION
**Pull request by hsiaoyi0504**
This can fix the installation error I met in #2. It's because the security issue mentioned in Chaosthebot/Chaos#491. I also used the local files to install container. Another thing is that I met following error messages during the installation:
``` shell
 Running setup.py install for remap-gff3
    /usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'project_urls'
      warnings.warn(msg)

    changing mode of /usr/local/bin/remap-gff3.py to 755
    changing mode of /usr/local/bin/get_remove_feature.py to 755
    changing mode of /usr/local/bin/gff_to_chain.py to 755
    changing mode of /usr/local/bin/re_construct_gff3_features.py to 755
  Running setup.py install for bx-python
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip_build_root/bx-python/setup.py", line 266, in <module>
        main()
      File "/tmp/pip_build_root/bx-python/setup.py", line 73, in main
        raise Exception( "numpy must be installed to build" )
    Exception: numpy must be installed to build
    Complete output from command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/bx-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tkiw4w-record/install-record.txt --single-version-externally-managed --compile:
    Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "/tmp/pip_build_root/bx-python/setup.py", line 266, in <module>

    main()

  File "/tmp/pip_build_root/bx-python/setup.py", line 73, in main

    raise Exception( "numpy must be installed to build" )

Exception: numpy must be installed to build

----------------------------------------
Cleaning up...
Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip_build_root/bx-python/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tkiw4w-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip_build_root/bx-python
Storing debug log for failure in /root/.pip/pip.log
The command '/bin/sh -c pip install --upgrade pip && pip install .' returned a non-zero code: 1
```

It seems to me that we still need to include numpy as dependencies.

### CODE REVIEW

**Comment by dytk2134** [comment]
I had updated the Dockerfile yesterday. Have you tried to build the image from the new Dockerfile(Fix_installation)? 
I can build the image successfully.
```
Successfully built remap-gff3 bx-python gff3 gff3tool
Installing collected packages: pysam, bx-python, cython, CrossMap, gff3, gff3tool, numpy, remap-gff3
Successfully installed CrossMap-0.2.7 bx-python-0.7.3 cython-0.28.2 gff3-0.3.0 gff3tool-1.3.0 numpy-1.14.3 pysam-0.14.1 remap-gff3-1.0.0
Removing intermediate container 6fa95b5f17c3
 ---> 013b066485f8
Successfully built 013b066485f8
Successfully tagged remap-gff3-image:latest
```
However, if I merge this branch, I will met the numpy error.

**Comment by hsiaoyi0504** [comment]
Well ... before I pushed this, you didn't push the new update, I will try again and report back.

**Comment by dytk2134** [comment]
dytk2134 committed a day ago
commit 63f6424a971138267fcd55d2a4d987f35c60da81
commit 0496ab5165ab9f44ed73a306778c9317271fd2d5

**Comment by hsiaoyi0504** [comment]
Changed back to **ubuntu:latest** works.

**Comment by hsiaoyi0504** [comment]
https://blog.cloud66.com/how-to-get-code-into-a-docker-container/

https://forums.docker.com/t/best-practices-for-getting-code-into-a-container-git-clone-vs-copy-vs-data-container/4077

**Pull request merged**
